version: "3"

services:
  server:
    image: matt/framework-x
    build: .
    environment:
      - MYSQLUSER=${MARIADB_USER}
      - MYSQLPASSWORD=${MARIADB_PASSWORD}
      - MYSQLHOST=mysql
      - MYSQLPORT=3306
      - MYSQLDATABASE=app
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mariadb:11
    restart: always
    healthcheck:
      interval: 1s
      retries: 90
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized"
        ]
      timeout: 90s
    volumes:
     - mysql_data:/var/lib/mysql
     - .docker/mariadb:/docker-entrypoint-initdb.d
    environment:
      - MARIADB_USER
      - MARIADB_PASSWORD
      - MARIADB_DATABASE=app
      - MARIADB_RANDOM_ROOT_PASSWORD=1

volumes:
  mysql_data:
